const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

// Must match the exact version pinned by `spm_dependency(...)` in
// react-native-telematics-sdk.podspec.
const TELEMATICS_SPM_URL = 'https://github.com/Mobile-Telematics/telematicsSDK-iOS-new-SPM.git';
const TELEMATICS_SPM_VERSION = '7.2.0';
const TELEMATICS_SPM_PRODUCT = 'TelematicsSDK';

// Guards both: (a) re-running `expo prebuild` against an already-patched
// Podfile (the dangerous mod pipeline applies on top of the existing file,
// it does not regenerate from a clean template unless `--clean` is passed),
// and (b) tells a human reader where this block came from.
const TELEMATICS_SPM_MARKER = '# @react-native-telematics-sdk spm-app-target-fix (do not edit -- managed by the react-native-telematics config plugin)';

const POST_INSTALL_REGEX = /^([ \t]*)post_install\s+do\s*\|[^|]*\|[ \t]*$/m;
const TARGET_BLOCK_REGEX = /^([ \t]*)target\s+(['"]).*?\2\s+do[ \t]*$/m;

/**
 * Attaches the TelematicsSDK Swift package PRODUCT to the app target itself,
 * not just the CocoaPods pod target.
 *
 * Why this is needed: `react-native-telematics-sdk.podspec` calls
 * `spm_dependency(...)` (see `node_modules/react-native/scripts/cocoapods/spm.rb`),
 * which registers the Swift package on the Pods project and attaches the
 * product dependency to the *pod target* (`react-native-telematics-sdk`).
 * Nothing attaches it to the *app target*, and CocoaPods'
 * `Pods-<App>-frameworks.sh` embed-frameworks script only embeds pods, not
 * SPM products. The result: the app binary links against
 * `@rpath/TelematicsSDK.framework/TelematicsSDK` but the framework is never
 * copied into `<App>.app/Frameworks/`, so the app builds fine and then
 * crashes at launch with a dyld "Library not loaded" error.
 *
 * The bare React Native example works around this with a manually-added
 * `XCRemoteSwiftPackageReference` / `XCSwiftPackageProductDependency` pair in
 * `TelematicsSdkExample.xcodeproj/project.pbxproj` (see the README's manual
 * Xcode step). On Expo, the `.pbxproj` is regenerated by every
 * `expo prebuild`, so that manual step has to be re-applied automatically --
 * this does it from a Podfile `post_install` hook using Xcodeproj (bundled
 * with CocoaPods), which has first-class Swift package support, unlike the
 * `xcode` npm package `@expo/config-plugins`' `withXcodeProject` is backed by.
 *
 * Appends into an existing `post_install do |installer| ... end` block when
 * the generated Podfile already has one (true for both the bare RN and Expo
 * templates, since `react_native_post_install` always needs one), or adds a
 * new block otherwise. Idempotent via `TELEMATICS_SPM_MARKER`: the injected
 * Ruby is also written to be safe to run on every `pod install` without
 * duplicating the package reference or product dependency.
 */
function withTelematicsPodfileSpmAppTarget(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const platformProjectRoot = config.modRequest.platformProjectRoot;
      const podfilePath = path.join(platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');

      ensureSpmAppTargetFix(podfilePath, contents);

      return config;
    },
  ]);
}

function buildSpmFixSnippet(bodyIndent) {
  const lines = [
    `${bodyIndent}${TELEMATICS_SPM_MARKER}`,
    `${bodyIndent}telematics_spm_url = '${TELEMATICS_SPM_URL}'`,
    `${bodyIndent}telematics_spm_requirement = { kind: 'exactVersion', version: '${TELEMATICS_SPM_VERSION}' }`,
    `${bodyIndent}telematics_spm_product = '${TELEMATICS_SPM_PRODUCT}'`,
    '',
    `${bodyIndent}installer.aggregate_targets`,
    `${bodyIndent}  .map { |t| t.user_project }`,
    `${bodyIndent}  .uniq { |p| p.path }`,
    `${bodyIndent}  .each do |telematics_project|`,
    `${bodyIndent}    telematics_app_target = telematics_project.targets.find do |t|`,
    `${bodyIndent}      t.respond_to?(:product_type) && t.product_type == 'com.apple.product-type.application'`,
    `${bodyIndent}    end`,
    `${bodyIndent}    next unless telematics_app_target`,
    '',
    `${bodyIndent}    telematics_pkg_class = Xcodeproj::Project::Object::XCRemoteSwiftPackageReference`,
    `${bodyIndent}    telematics_dep_class = Xcodeproj::Project::Object::XCSwiftPackageProductDependency`,
    '',
    `${bodyIndent}    telematics_pkg = telematics_project.root_object.package_references.find do |ref|`,
    `${bodyIndent}      ref.is_a?(telematics_pkg_class) && ref.repositoryURL == telematics_spm_url`,
    `${bodyIndent}    end`,
    `${bodyIndent}    unless telematics_pkg`,
    `${bodyIndent}      telematics_pkg = telematics_project.new(telematics_pkg_class)`,
    `${bodyIndent}      telematics_pkg.repositoryURL = telematics_spm_url`,
    `${bodyIndent}      telematics_pkg.requirement = telematics_spm_requirement`,
    `${bodyIndent}      telematics_project.root_object.package_references << telematics_pkg`,
    `${bodyIndent}    end`,
    '',
    `${bodyIndent}    telematics_existing_dep = telematics_app_target.package_product_dependencies.find do |dep|`,
    `${bodyIndent}      dep.is_a?(telematics_dep_class) && dep.package == telematics_pkg && dep.product_name == telematics_spm_product`,
    `${bodyIndent}    end`,
    `${bodyIndent}    unless telematics_existing_dep`,
    `${bodyIndent}      telematics_dep = telematics_project.new(telematics_dep_class)`,
    `${bodyIndent}      telematics_dep.package = telematics_pkg`,
    `${bodyIndent}      telematics_dep.product_name = telematics_spm_product`,
    `${bodyIndent}      telematics_app_target.package_product_dependencies << telematics_dep`,
    `${bodyIndent}    end`,
    '',
    `${bodyIndent}    telematics_project.save`,
    `${bodyIndent}  end`,
  ];
  return lines.join('\n');
}

function ensureSpmAppTargetFix(podfilePath, contents) {
  if (contents.includes(TELEMATICS_SPM_MARKER)) {
    return; // Already applied (e.g. by a previous prebuild run) -- idempotent no-op.
  }

  const postInstallMatch = POST_INSTALL_REGEX.exec(contents);

  if (postInstallMatch) {
    const indent = postInstallMatch[1];
    const blockBodyStart = postInstallMatch.index + postInstallMatch[0].length;
    const closingEndIndex = findMatchingEnd(contents, blockBodyStart, indent);
    if (closingEndIndex == null) {
      throw new Error(
        `[react-native-telematics] Could not find the closing "end" for the existing "post_install do" block in ` +
          `${podfilePath}. Please add the TelematicsSDK SPM app-target fix manually (see README).`
      );
    }

    const snippet = buildSpmFixSnippet(`${indent}  `);
    const updated =
      contents.slice(0, closingEndIndex) + snippet + '\n' + contents.slice(closingEndIndex);
    fs.writeFileSync(podfilePath, updated);
    return;
  }

  // No post_install block at all -- add one inside the app target block.
  const targetMatch = TARGET_BLOCK_REGEX.exec(contents);
  if (!targetMatch) {
    throw new Error(
      `[react-native-telematics] Could not find a "target '...' do" block in ${podfilePath} to attach a ` +
        '"post_install" hook to. Please add the TelematicsSDK SPM app-target fix manually (see README).'
    );
  }

  const targetIndent = targetMatch[1];
  const bodyIndent = `${targetIndent}  `;
  const targetBodyStart = targetMatch.index + targetMatch[0].length;
  const targetClosingEndIndex = findMatchingEnd(contents, targetBodyStart, targetIndent);
  if (targetClosingEndIndex == null) {
    throw new Error(
      `[react-native-telematics] Could not find the closing "end" for the app target block in ${podfilePath}. ` +
        'Please add the TelematicsSDK SPM app-target fix manually (see README).'
    );
  }

  const newBlock =
    `${bodyIndent}post_install do |installer|\n` +
    buildSpmFixSnippet(`${bodyIndent}  `) +
    `\n${bodyIndent}end\n`;
  const updated =
    contents.slice(0, targetClosingEndIndex) + newBlock + contents.slice(targetClosingEndIndex);
  fs.writeFileSync(podfilePath, updated);
}

/**
 * Finds the index (into `contents`) of the start of the first line at or
 * after `fromIndex` that is exactly `${indent}end` -- i.e. the `end` closing
 * a `do`/`target` block opened at indentation level `indent`. Relies on the
 * Podfile being formatted consistently (as every RN/Expo template is), so a
 * nested block's `end` is always indented further than its opener's.
 */
function findMatchingEnd(contents, fromIndex, indent) {
  const closingEndRegex = new RegExp(`^${escapeRegExp(indent)}end[ \\t]*$`, 'm');
  const rest = contents.slice(fromIndex);
  const match = closingEndRegex.exec(rest);
  return match ? fromIndex + match.index : null;
}

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = withTelematicsPodfileSpmAppTarget;
