source 'https://github.com/CocoaPods/Specs.git'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :dynamic


target 'TelematicsSdkExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :new_arch_enabled => true
  )

  pod 'react-native-telematics-sdk', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.80.0' })
  
  post_install do |installer|
#    §flipper_post_install(installer)
        # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Ensure TelematicsSDK SPM binary framework is also added to the app target.
    # Without this, the app may link against a dynamic TelematicsSDK.framework
    # (via a pod target) but not embed it into the final .app, causing a dyld crash.
    
    # telematics_spm_url = 'https://github.com/Mobile-Telematics/telematicsSDK-iOS-new-SPM.git'
    # telematics_spm_requirement = { kind: 'exactVersion', version: '7.0.3' }
    # telematics_spm_product = 'TelematicsSDK'

    # installer.aggregate_targets
    #   .map { |t| t.user_project }
    #   .uniq { |p| p.path }
    #   .each do |project|
    #     app_target = project.targets.find { |t| t.name == 'TelematicsSdkExample' }
    #     next unless app_target

    #     pkg_class = Xcodeproj::Project::Object::XCRemoteSwiftPackageReference
    #     ref_class = Xcodeproj::Project::Object::XCSwiftPackageProductDependency

    #     pkg = project.root_object.package_references.find { |p| p.class == pkg_class && p.repositoryURL == telematics_spm_url }
    #     unless pkg
    #       pkg = project.new(pkg_class)
    #       pkg.repositoryURL = telematics_spm_url
    #       pkg.requirement = telematics_spm_requirement
    #       project.root_object.package_references << pkg
    #     end

    #     already = app_target.package_product_dependencies.find do |r|
    #       r.class == ref_class && r.package == pkg && r.product_name == telematics_spm_product
    #     end
    #     unless already
    #       ref = project.new(ref_class)
    #       ref.package = pkg
    #       ref.product_name = telematics_spm_product
    #       app_target.package_product_dependencies << ref
    #     end

    #     project.save
    #   end

    # Workaround for Xcode 26: newer Apple Clang breaks consteval in fmt 11.0.2.

    # Patch base.h to disable consteval since the header doesn't check for pre-defined FMT_USE_CONSTEVAL.

    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')

    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('Xcode 26 workaround')
        patched = content.gsub(
          /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
          "// Xcode 26 workaround: disable consteval\n\\1 0"
        )
        if patched != content
          File.chmod(0644, fmt_base)
          File.write(fmt_base, patched)
        end
      end
    end
  
    #Uncomment this for M1 Apple
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    #      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    #      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    #      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
       
    #   end
    # end
  end
end
