require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'


target 'TelematicsSdkExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-telematics-sdk', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.80.0' })
  
  post_install do |installer|
#    §flipper_post_install(installer)
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  
    #Uncomment this for M1 Apple
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    #      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    #      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    #      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
       
    #   end
    # end
  end
end
